run_name: cloud
defaults:
  - config_schema

data:
  data_path: /home/gustav5_hansen5/DEEP_BIOMED/covid_data.nosync/data
  input_img_size: 96
  crop_volume_size: 256
  prob_foreground_center: 0.95

training:
  device: cuda
  train_batch_size: 16
  val_batch_size: 16
  batches_per_epoch: 100
  num_epochs: 200
  loss_fn_name: maskedDiceLoss

optimizer:
  learning_rate: 0.0001

model:
  model_type: unetr